export type NeuralNodeType =
  | "core"
  | "system"
  | "kernel"
  | "service"
  | "interface"
  | "hardware"
  | "ai"
  | "memory"
  | "network"
  | "audio"
  | "package"
  | "log"
  | "action";

export type NeuralNodeStatus =
  | "idle"
  | "ready"
  | "thinking"
  | "approval"
  | "running"
  | "success"
  | "warning"
  | "danger"
  | "error";

export interface NeuralNode {
  id: string;
  label: string;
  type: NeuralNodeType;
  status: NeuralNodeStatus;
  description: string;
  depth: number;
  parentId?: string;
  position: [number, number, number];
  diagnosticsKey?: string;
  children?: string[];
}

export interface NeuralConnection {
  id: string;
  from: string;
  to: string;
  status: NeuralNodeStatus;
  label?: string;
  strength: number;
}

function node(input: NeuralNode): NeuralNode {
  return input;
}

export const neuralNodes: NeuralNode[] = [
  node({
    id: "core",
    label: "AILU NEURAL CORE",
    type: "core",
    status: "ready",
    description: "Nucleo neural local. Camada conversacional, mapa 3D e executor aprovado.",
    depth: 0,
    position: [0, 0, 0],
    diagnosticsKey: "system-overview",
    children: ["system", "interface", "hardware", "connectivity", "audio", "ai", "memory"],
  }),
  node({
    id: "system",
    label: "SYSTEM",
    type: "system",
    status: "idle",
    description: "Regiao operacional do Arch: kernel, systemd e pacotes.",
    depth: 1,
    parentId: "core",
    position: [-4.8, 1.2, -1.6],
    diagnosticsKey: "system-overview",
    children: ["kernel", "systemd", "packages"],
  }),
  node({
    id: "interface",
    label: "INTERFACE",
    type: "interface",
    status: "idle",
    description: "Sessao visual: Hyprland, Quickshell, workspaces e configs.",
    depth: 1,
    parentId: "core",
    position: [-2.5, 2.7, 3.4],
    diagnosticsKey: "hyprland",
    children: ["hyprland", "quickshell"],
  }),
  node({
    id: "hardware",
    label: "HARDWARE",
    type: "hardware",
    status: "idle",
    description: "CPU, GPU, memoria, ZRAM e armazenamento.",
    depth: 1,
    parentId: "core",
    position: [2.7, 2.2, -3.2],
    diagnosticsKey: "ram-zram",
    children: ["cpu", "gpu", "ram-zram", "zram", "disk"],
  }),
  node({
    id: "connectivity",
    label: "CONNECTIVITY",
    type: "network",
    status: "idle",
    description: "Rede, Bluetooth e DNS como camada de conexao do sistema.",
    depth: 1,
    parentId: "core",
    position: [-3.8, -2.5, 2.3],
    diagnosticsKey: "network",
    children: ["network", "bluetooth", "dns"],
  }),
  node({
    id: "audio",
    label: "AUDIO",
    type: "audio",
    status: "idle",
    description: "PipeWire, WirePlumber e dispositivos de audio.",
    depth: 1,
    parentId: "core",
    position: [3.4, -1.6, 3.0],
    diagnosticsKey: "audio",
    children: ["pipewire", "wireplumber", "audio-devices"],
  }),
  node({
    id: "ai",
    label: "AI",
    type: "ai",
    status: "ready",
    description: "Ollama local, modelos, workers e providers futuros.",
    depth: 1,
    parentId: "core",
    position: [4.7, 1.0, 0.2],
    diagnosticsKey: "ollama",
    children: ["ollama", "models", "workers", "providers"],
  }),
  node({
    id: "memory",
    label: "MEMORY",
    type: "memory",
    status: "idle",
    description: "Acoes, logs, relacoes e contrato Graphiti-ready.",
    depth: 1,
    parentId: "core",
    position: [0.0, -3.7, -2.4],
    children: ["actions", "logs", "relations", "graphiti-ready"],
  }),

  node({
    id: "kernel",
    label: "KERNEL",
    type: "kernel",
    status: "idle",
    description: "Versao, boot, cmdline, modulos e journal do kernel.",
    depth: 2,
    parentId: "system",
    position: [-7.0, 2.0, -2.4],
    diagnosticsKey: "kernel",
    children: ["journal-kernel", "kernel-modules", "cmdline", "boot"],
  }),
  node({
    id: "systemd",
    label: "SYSTEMD",
    type: "service",
    status: "idle",
    description: "Servicos, unidades falhando e journal do boot atual.",
    depth: 2,
    parentId: "system",
    position: [-6.6, 0.1, 0.3],
    diagnosticsKey: "systemd",
    children: ["failed-units", "services", "journal"],
  }),
  node({
    id: "packages",
    label: "PACKAGES",
    type: "package",
    status: "idle",
    description: "Pacman, Yay, updates e cache de pacotes.",
    depth: 2,
    parentId: "system",
    position: [-5.2, 2.9, 1.2],
    diagnosticsKey: "packages",
    children: ["pacman", "yay", "updates", "pacman-cache", "aur-updates"],
  }),
  node({
    id: "hyprland",
    label: "HYPRLAND",
    type: "interface",
    status: "idle",
    description: "Compositor Wayland, monitores, workspaces, clients e configs.",
    depth: 2,
    parentId: "interface",
    position: [-3.4, 4.7, 4.8],
    diagnosticsKey: "hyprland",
    children: ["monitors", "workspaces", "clients", "configs"],
  }),
  node({
    id: "quickshell",
    label: "QUICKSHELL",
    type: "interface",
    status: "idle",
    description: "Shell End-4/Quickshell, QML, logs e reload.",
    depth: 2,
    parentId: "interface",
    position: [-0.9, 4.3, 5.0],
    children: ["qml", "quickshell-logs", "reload", "end4-shell"],
  }),
  node({
    id: "cpu",
    label: "CPU",
    type: "hardware",
    status: "idle",
    description: "Load, processos e pressao de CPU.",
    depth: 2,
    parentId: "hardware",
    position: [1.2, 4.3, -4.8],
    diagnosticsKey: "system-overview",
  }),
  node({
    id: "gpu",
    label: "GPU",
    type: "hardware",
    status: "idle",
    description: "GPU detectada, Mesa/RADV e relacao com Hyprland.",
    depth: 2,
    parentId: "hardware",
    position: [4.7, 3.4, -4.6],
    diagnosticsKey: "gpu",
    children: ["mesa", "vulkan", "hypr-gpu"],
  }),
  node({
    id: "ram-zram",
    label: "RAM",
    type: "hardware",
    status: "idle",
    description: "Uso de RAM, pressao e relacao com ZRAM.",
    depth: 2,
    parentId: "hardware",
    position: [1.9, 1.5, -5.6],
    diagnosticsKey: "ram-zram",
    children: ["memory-pressure", "swapon"],
  }),
  node({
    id: "zram",
    label: "ZRAM",
    type: "hardware",
    status: "idle",
    description: "Swap comprimido em RAM, prioridade e dispositivos.",
    depth: 2,
    parentId: "hardware",
    position: [3.7, 0.4, -5.8],
    diagnosticsKey: "ram-zram",
    children: ["zramctl", "swapon"],
  }),
  node({
    id: "disk",
    label: "DISK",
    type: "hardware",
    status: "idle",
    description: "Blocos, filesystems, uso e armazenamento local.",
    depth: 2,
    parentId: "hardware",
    position: [5.1, 1.9, -2.7],
    diagnosticsKey: "disk",
    children: ["lsblk", "disk-usage"],
  }),
  node({
    id: "network",
    label: "NETWORK",
    type: "network",
    status: "idle",
    description: "Dispositivos NetworkManager e conectividade.",
    depth: 2,
    parentId: "connectivity",
    position: [-5.7, -4.0, 2.8],
    diagnosticsKey: "network",
    children: ["nm-devices", "dns-route"],
  }),
  node({
    id: "bluetooth",
    label: "BLUETOOTH",
    type: "network",
    status: "idle",
    description: "Controladores, rfkill e estado Bluetooth.",
    depth: 2,
    parentId: "connectivity",
    position: [-3.6, -4.9, 4.3],
    diagnosticsKey: "bluetooth",
    children: ["bt-rfkill", "bt-controller", "bt-systemd"],
  }),
  node({
    id: "dns",
    label: "DNS",
    type: "network",
    status: "idle",
    description: "Resolucao, rota e conectividade futura.",
    depth: 2,
    parentId: "connectivity",
    position: [-2.2, -3.7, 2.8],
    diagnosticsKey: "network",
  }),
  node({
    id: "pipewire",
    label: "PIPEWIRE",
    type: "audio",
    status: "idle",
    description: "Servidor de audio/video da sessao.",
    depth: 2,
    parentId: "audio",
    position: [5.6, -2.4, 4.0],
    diagnosticsKey: "audio",
  }),
  node({
    id: "wireplumber",
    label: "WIREPLUMBER",
    type: "audio",
    status: "idle",
    description: "Session manager do PipeWire.",
    depth: 2,
    parentId: "audio",
    position: [3.4, -3.8, 5.0],
    diagnosticsKey: "audio",
  }),
  node({
    id: "audio-devices",
    label: "DEVICES",
    type: "audio",
    status: "idle",
    description: "Sinks, sources e dispositivos expostos pelo PipeWire.",
    depth: 2,
    parentId: "audio",
    position: [2.2, -1.8, 5.5],
    diagnosticsKey: "audio",
  }),
  node({
    id: "ollama",
    label: "OLLAMA",
    type: "ai",
    status: "ready",
    description: "Provider local inicial via API http://localhost:11434.",
    depth: 2,
    parentId: "ai",
    position: [7.0, 1.3, 0.2],
    diagnosticsKey: "ollama",
    children: ["local-models", "qwen-coder"],
  }),
  node({
    id: "models",
    label: "MODELS",
    type: "ai",
    status: "idle",
    description: "Catalogo local de modelos e runtime alvo.",
    depth: 2,
    parentId: "ai",
    position: [5.9, 2.8, -1.6],
    diagnosticsKey: "ollama",
    children: ["local-models", "qwen-coder"],
  }),
  node({
    id: "workers",
    label: "WORKERS",
    type: "ai",
    status: "idle",
    description: "Operarias futuras: system, code, fast, heavy e vision.",
    depth: 2,
    parentId: "ai",
    position: [5.6, -0.6, -1.4],
  }),
  node({
    id: "providers",
    label: "PROVIDERS",
    type: "ai",
    status: "idle",
    description: "Providers locais e futuros adaptadores de IA.",
    depth: 2,
    parentId: "ai",
    position: [6.2, 0.0, 2.2],
    diagnosticsKey: "ollama",
  }),
  node({
    id: "actions",
    label: "ACTIONS",
    type: "action",
    status: "idle",
    description: "Planos, aprovacoes, execucoes e historico operacional.",
    depth: 2,
    parentId: "memory",
    position: [1.8, -5.4, -3.0],
    children: ["approval-layer", "action-logs"],
  }),
  node({
    id: "logs",
    label: "LOGS",
    type: "log",
    status: "idle",
    description: "Journals, stdout/stderr e eventos do mapa neural.",
    depth: 2,
    parentId: "memory",
    position: [-2.1, -5.2, -3.1],
    diagnosticsKey: "kernel-logs",
    children: ["journal-errors", "kernel-logs"],
  }),
  node({
    id: "relations",
    label: "RELATIONS",
    type: "memory",
    status: "idle",
    description: "Arestas locais entre sintomas, nos e acoes.",
    depth: 2,
    parentId: "memory",
    position: [-0.4, -6.2, -1.0],
  }),
  node({
    id: "graphiti-ready",
    label: "GRAPHITI-READY",
    type: "memory",
    status: "idle",
    description: "Contrato preparado para memoria temporal Graphiti futura.",
    depth: 2,
    parentId: "memory",
    position: [0.8, -5.8, -5.1],
  }),

  node({
    id: "journal-kernel",
    label: "JOURNAL-KERNEL",
    type: "log",
    status: "idle",
    description: "Eventos recentes do kernel para triagem tecnica.",
    depth: 3,
    parentId: "kernel",
    position: [-9.0, 2.5, -3.6],
    diagnosticsKey: "kernel-logs",
  }),
  node({
    id: "kernel-logs",
    label: "KERNEL LOGS",
    type: "log",
    status: "idle",
    description: "Alias operacional para logs do kernel.",
    depth: 3,
    parentId: "logs",
    position: [-3.4, -6.6, -4.4],
    diagnosticsKey: "kernel-logs",
  }),
  node({
    id: "kernel-modules",
    label: "MODULES",
    type: "kernel",
    status: "idle",
    description: "Modulos relacionados a hardware e boot.",
    depth: 3,
    parentId: "kernel",
    position: [-8.7, 3.7, -1.8],
  }),
  node({
    id: "cmdline",
    label: "CMDLINE",
    type: "kernel",
    status: "idle",
    description: "Parametros de boot e kernel cmdline.",
    depth: 3,
    parentId: "kernel",
    position: [-7.8, 1.1, -4.1],
  }),
  node({
    id: "boot",
    label: "BOOT",
    type: "kernel",
    status: "idle",
    description: "Estado de boot e relacoes futuras com loader.",
    depth: 3,
    parentId: "kernel",
    position: [-7.6, 3.3, -4.2],
  }),
  node({
    id: "failed-units",
    label: "FAILED-UNITS",
    type: "service",
    status: "idle",
    description: "Unidades systemd em falha.",
    depth: 3,
    parentId: "systemd",
    position: [-8.8, -0.5, 0.7],
    diagnosticsKey: "systemd",
  }),
  node({
    id: "services",
    label: "SERVICES",
    type: "service",
    status: "idle",
    description: "Servicos systemd ativos e futuros alvos de acao.",
    depth: 3,
    parentId: "systemd",
    position: [-7.3, -1.4, 2.2],
    diagnosticsKey: "systemd",
  }),
  node({
    id: "journal",
    label: "JOURNAL",
    type: "log",
    status: "idle",
    description: "Journal do boot atual.",
    depth: 3,
    parentId: "systemd",
    position: [-6.2, -1.0, -1.4],
    diagnosticsKey: "kernel-logs",
  }),
  node({
    id: "journal-errors",
    label: "JOURNAL ERRORS",
    type: "log",
    status: "idle",
    description: "Erros recentes de alta prioridade.",
    depth: 3,
    parentId: "logs",
    position: [-1.5, -6.9, -4.3],
    diagnosticsKey: "kernel-logs",
  }),
  node({
    id: "pacman",
    label: "PACMAN",
    type: "package",
    status: "idle",
    description: "Gerenciador oficial de pacotes.",
    depth: 3,
    parentId: "packages",
    position: [-6.4, 4.7, 1.2],
    diagnosticsKey: "packages",
  }),
  node({
    id: "yay",
    label: "YAY",
    type: "package",
    status: "idle",
    description: "AUR helper quando disponivel.",
    depth: 3,
    parentId: "packages",
    position: [-4.6, 4.9, 2.3],
    diagnosticsKey: "packages",
  }),
  node({
    id: "updates",
    label: "UPDATES",
    type: "package",
    status: "idle",
    description: "Updates oficiais e AUR.",
    depth: 3,
    parentId: "packages",
    position: [-4.0, 3.8, 0.0],
    diagnosticsKey: "packages",
  }),
  node({
    id: "pacman-cache",
    label: "PACMAN CACHE",
    type: "package",
    status: "idle",
    description: "Cache de pacotes e limpeza planejada.",
    depth: 3,
    parentId: "packages",
    position: [-6.2, 3.5, 3.0],
    diagnosticsKey: "packages",
  }),
  node({
    id: "aur-updates",
    label: "AUR UPDATES",
    type: "package",
    status: "idle",
    description: "Atualizacoes AUR via yay.",
    depth: 3,
    parentId: "packages",
    position: [-3.6, 2.8, 2.6],
    diagnosticsKey: "packages",
  }),
  node({
    id: "monitors",
    label: "MONITORS",
    type: "interface",
    status: "idle",
    description: "Monitores ativos no Hyprland.",
    depth: 3,
    parentId: "hyprland",
    position: [-4.8, 6.1, 5.8],
    diagnosticsKey: "hyprland",
  }),
  node({
    id: "workspaces",
    label: "WORKSPACES",
    type: "interface",
    status: "idle",
    description: "Workspaces e layout atual.",
    depth: 3,
    parentId: "hyprland",
    position: [-2.9, 6.6, 6.2],
    diagnosticsKey: "hyprland",
  }),
  node({
    id: "clients",
    label: "CLIENTS",
    type: "interface",
    status: "idle",
    description: "Janelas clientes abertas.",
    depth: 3,
    parentId: "hyprland",
    position: [-1.4, 5.8, 5.3],
    diagnosticsKey: "hyprland",
  }),
  node({
    id: "configs",
    label: "CONFIGS",
    type: "interface",
    status: "idle",
    description: "Configs futuras com fluxo de aprovacao.",
    depth: 3,
    parentId: "hyprland",
    position: [-4.1, 5.4, 7.3],
  }),
  node({
    id: "qml",
    label: "QML",
    type: "interface",
    status: "idle",
    description: "Arquivos QML do shell.",
    depth: 3,
    parentId: "quickshell",
    position: [-1.4, 6.0, 6.6],
  }),
  node({
    id: "quickshell-logs",
    label: "QS LOGS",
    type: "log",
    status: "idle",
    description: "Logs futuros do Quickshell.",
    depth: 3,
    parentId: "quickshell",
    position: [0.3, 5.6, 6.5],
  }),
  node({
    id: "reload",
    label: "RELOAD",
    type: "action",
    status: "idle",
    description: "Reload futuro com Approval se alterar estado.",
    depth: 3,
    parentId: "quickshell",
    position: [0.8, 4.2, 6.6],
  }),
  node({
    id: "end4-shell",
    label: "END-4",
    type: "interface",
    status: "idle",
    description: "Camada End-4/Quickshell.",
    depth: 3,
    parentId: "quickshell",
    position: [-1.2, 3.4, 6.6],
  }),
  node({
    id: "mesa",
    label: "MESA",
    type: "hardware",
    status: "idle",
    description: "Stack grafica Mesa/RADV quando aplicavel.",
    depth: 3,
    parentId: "gpu",
    position: [6.4, 4.6, -5.4],
    diagnosticsKey: "gpu",
  }),
  node({
    id: "vulkan",
    label: "VULKAN",
    type: "hardware",
    status: "idle",
    description: "Capabilities graficas futuras.",
    depth: 3,
    parentId: "gpu",
    position: [4.5, 5.2, -6.2],
    diagnosticsKey: "gpu",
  }),
  node({
    id: "hypr-gpu",
    label: "HYPR/GPU",
    type: "interface",
    status: "idle",
    description: "Relacao entre compositor, monitor e GPU.",
    depth: 3,
    parentId: "gpu",
    position: [6.6, 2.8, -3.6],
    diagnosticsKey: "hyprland",
  }),
  node({
    id: "memory-pressure",
    label: "PRESSURE",
    type: "hardware",
    status: "idle",
    description: "Indicadores futuros de pressao de memoria.",
    depth: 3,
    parentId: "ram-zram",
    position: [1.2, 0.1, -7.2],
    diagnosticsKey: "ram-zram",
  }),
  node({
    id: "swapon",
    label: "SWAPON",
    type: "hardware",
    status: "idle",
    description: "Swap ativo e prioridades.",
    depth: 3,
    parentId: "ram-zram",
    position: [2.8, 0.1, -7.3],
    diagnosticsKey: "ram-zram",
  }),
  node({
    id: "zramctl",
    label: "ZRAMCTL",
    type: "hardware",
    status: "idle",
    description: "Dispositivos zram e uso comprimido.",
    depth: 3,
    parentId: "zram",
    position: [4.4, -0.8, -7.2],
    diagnosticsKey: "ram-zram",
  }),
  node({
    id: "lsblk",
    label: "LSBLK",
    type: "hardware",
    status: "idle",
    description: "Topologia de blocos.",
    depth: 3,
    parentId: "disk",
    position: [6.8, 2.6, -2.7],
    diagnosticsKey: "disk",
  }),
  node({
    id: "disk-usage",
    label: "DF -H",
    type: "hardware",
    status: "idle",
    description: "Uso de disco por filesystem.",
    depth: 3,
    parentId: "disk",
    position: [6.4, 1.2, -1.0],
    diagnosticsKey: "disk",
  }),
  node({
    id: "nm-devices",
    label: "NMCLI",
    type: "network",
    status: "idle",
    description: "Dispositivos NetworkManager.",
    depth: 3,
    parentId: "network",
    position: [-7.4, -5.0, 3.4],
    diagnosticsKey: "network",
  }),
  node({
    id: "dns-route",
    label: "ROUTE",
    type: "network",
    status: "idle",
    description: "Rota e DNS futuros.",
    depth: 3,
    parentId: "network",
    position: [-5.4, -5.9, 1.7],
    diagnosticsKey: "network",
  }),
  node({
    id: "bt-rfkill",
    label: "RFKILL",
    type: "network",
    status: "idle",
    description: "Bloqueios de radio.",
    depth: 3,
    parentId: "bluetooth",
    position: [-4.6, -6.6, 5.2],
    diagnosticsKey: "bluetooth",
  }),
  node({
    id: "bt-controller",
    label: "CONTROLLER",
    type: "network",
    status: "idle",
    description: "Controlador Bluetooth detectado.",
    depth: 3,
    parentId: "bluetooth",
    position: [-2.7, -6.2, 5.6],
    diagnosticsKey: "bluetooth",
  }),
  node({
    id: "bt-systemd",
    label: "BT SERVICE",
    type: "service",
    status: "idle",
    description: "Servico bluetooth no systemd.",
    depth: 3,
    parentId: "bluetooth",
    position: [-2.2, -4.7, 6.0],
    diagnosticsKey: "systemd",
  }),
  node({
    id: "local-models",
    label: "LOCAL MODELS",
    type: "ai",
    status: "idle",
    description: "Modelos instalados no Ollama.",
    depth: 3,
    parentId: "ollama",
    position: [8.6, 2.2, -0.4],
    diagnosticsKey: "ollama",
  }),
  node({
    id: "qwen-coder",
    label: "QWEN CODER",
    type: "ai",
    status: "ready",
    description: "Modelo padrao do MVP para planejamento.",
    depth: 3,
    parentId: "ollama",
    position: [8.1, 0.3, 1.0],
    diagnosticsKey: "ollama",
  }),
  node({
    id: "approval-layer",
    label: "APPROVAL",
    type: "action",
    status: "approval",
    description: "Autorizacao explicita antes de alterar o sistema.",
    depth: 3,
    parentId: "actions",
    position: [3.0, -6.5, -3.8],
  }),
  node({
    id: "action-logs",
    label: "ACTION LOGS",
    type: "log",
    status: "idle",
    description: "Stdout, stderr, exit code e duracao.",
    depth: 3,
    parentId: "actions",
    position: [1.3, -7.0, -4.6],
  }),
];

export const neuralConnections: NeuralConnection[] = neuralNodes
  .filter((item) => item.parentId)
  .map((item) => ({
    id: `${item.parentId}-${item.id}`,
    from: item.parentId ?? "core",
    to: item.id,
    status: item.status,
    label: item.label,
    strength: item.depth === 1 ? 0.94 : item.depth === 2 ? 0.68 : 0.46,
  }));

export const nodeById = new Map(neuralNodes.map((item) => [item.id, item]));

export function getNodePath(nodeId: string): NeuralNode[] {
  const path: NeuralNode[] = [];
  let current = nodeById.get(nodeId);
  while (current) {
    path.unshift(current);
    current = current.parentId ? nodeById.get(current.parentId) : undefined;
  }
  return path;
}

export function getChildNodes(nodeId: string): NeuralNode[] {
  const node = nodeById.get(nodeId);
  return node?.children?.map((childId) => nodeById.get(childId)).filter(isNode) ?? [];
}

export function getRelatedNodeIds(nodeId: string): string[] {
  const node = nodeById.get(nodeId);
  const parent = node?.parentId ? [node.parentId] : [];
  return [...new Set([...parent, ...(node?.children ?? [])])];
}

function isNode(value: NeuralNode | undefined): value is NeuralNode {
  return Boolean(value);
}
