export type NeuralNodeType =
  | "core"
  | "system"
  | "kernel"
  | "service"
  | "interface"
  | "hardware"
  | "ai"
  | "memory"
  | "network"
  | "audio"
  | "package"
  | "log"
  | "action";

export type NeuralNodeStatus =
  | "idle"
  | "ready"
  | "thinking"
  | "approval"
  | "running"
  | "success"
  | "warning"
  | "danger"
  | "error";

export interface NeuralNode {
  id: string;
  label: string;
  type: NeuralNodeType;
  status: NeuralNodeStatus;
  description: string;
  depth: number;
  parentId?: string;
  position: [number, number, number];
  diagnosticsKey?: string;
  children?: string[];
}

export interface NeuralConnection {
  id: string;
  from: string;
  to: string;
  status: NeuralNodeStatus;
  label?: string;
  strength: number;
}

export const neuralNodes: NeuralNode[] = [
  {
    id: "core",
    label: "AILU NEURAL CORE",
    type: "core",
    status: "ready",
    description: "Nucleo central local. Runtime Ollama Local, modelo qwen2.5-coder:1.5b.",
    depth: 0,
    position: [0, 0, 0],
    diagnosticsKey: "system-overview",
    children: [
      "kernel",
      "systemd",
      "hyprland",
      "quickshell",
      "packages",
      "ollama",
      "memory",
      "bluetooth",
      "network",
      "audio",
      "gpu",
      "ram-zram",
      "disk",
      "logs",
      "actions",
    ],
  },
  {
    id: "kernel",
    label: "Kernel",
    type: "kernel",
    status: "idle",
    description: "Versao, flavor e eventos recentes do kernel.",
    depth: 1,
    parentId: "core",
    position: [-4.8, 1.8, -1.2],
    diagnosticsKey: "kernel",
    children: ["kernel-logs", "kernel-modules"],
  },
  {
    id: "systemd",
    label: "Systemd",
    type: "service",
    status: "idle",
    description: "Unidades falhando, status de servicos e boot atual.",
    depth: 1,
    parentId: "core",
    position: [-3.4, -1.9, 2.4],
    diagnosticsKey: "systemd",
    children: ["failed-units", "journal-errors"],
  },
  {
    id: "hyprland",
    label: "Hyprland",
    type: "interface",
    status: "idle",
    description: "Compositor Wayland, monitores, workspaces e clients.",
    depth: 1,
    parentId: "core",
    position: [-1.4, 2.7, 3.4],
    diagnosticsKey: "hyprland",
    children: ["monitors", "workspaces", "clients"],
  },
  {
    id: "quickshell",
    label: "Quickshell",
    type: "interface",
    status: "idle",
    description: "Camada visual End-4/Quickshell e integracoes da sessao.",
    depth: 1,
    parentId: "core",
    position: [1.7, -2.6, 3.3],
    children: ["end4-shell", "dock-events"],
  },
  {
    id: "packages",
    label: "Pacman/Yay",
    type: "package",
    status: "idle",
    description: "Pacotes, updates, cache e operacoes planejadas.",
    depth: 1,
    parentId: "core",
    position: [4.7, 1.6, -1.4],
    diagnosticsKey: "packages",
    children: ["pacman-cache", "aur-updates"],
  },
  {
    id: "ollama",
    label: "Ollama",
    type: "ai",
    status: "ready",
    description: "Provider local inicial para planos estruturados.",
    depth: 1,
    parentId: "core",
    position: [3.1, -2.1, -3.1],
    diagnosticsKey: "ollama",
    children: ["local-models", "qwen-coder"],
  },
  {
    id: "memory",
    label: "Memory",
    type: "memory",
    status: "idle",
    description: "Memoria operacional local e arestas Graphiti-ready.",
    depth: 1,
    parentId: "core",
    position: [0.1, 3.5, -3.4],
    children: ["memory-edges", "graphiti-ready"],
  },
  {
    id: "bluetooth",
    label: "Bluetooth",
    type: "hardware",
    status: "idle",
    description: "Controladores, rfkill e estado bluetoothctl.",
    depth: 1,
    parentId: "core",
    position: [-5.1, -1.0, -3.0],
    diagnosticsKey: "bluetooth",
    children: ["bt-rfkill", "bt-controller", "bt-systemd"],
  },
  {
    id: "network",
    label: "Network",
    type: "network",
    status: "idle",
    description: "Dispositivos e conectividade via NetworkManager.",
    depth: 1,
    parentId: "core",
    position: [-2.0, -3.7, -1.7],
    diagnosticsKey: "network",
    children: ["nm-devices", "dns-route"],
  },
  {
    id: "audio",
    label: "Audio",
    type: "audio",
    status: "idle",
    description: "PipeWire, WirePlumber, sinks e sources.",
    depth: 1,
    parentId: "core",
    position: [2.2, 3.2, 2.0],
    diagnosticsKey: "audio",
    children: ["pipewire", "wireplumber"],
  },
  {
    id: "gpu",
    label: "GPU",
    type: "hardware",
    status: "idle",
    description: "GPU detectada, drivers e relacao com Hyprland.",
    depth: 1,
    parentId: "core",
    position: [5.0, -0.9, 2.2],
    diagnosticsKey: "gpu",
    children: ["mesa", "vulkan", "hypr-gpu"],
  },
  {
    id: "ram-zram",
    label: "RAM/ZRAM",
    type: "hardware",
    status: "idle",
    description: "Uso de memoria, swap e dispositivos zram.",
    depth: 1,
    parentId: "core",
    position: [-0.5, -4.0, 1.0],
    diagnosticsKey: "ram-zram",
    children: ["swapon", "zramctl", "memory-pressure"],
  },
  {
    id: "disk",
    label: "Disk",
    type: "hardware",
    status: "idle",
    description: "Volumes, particoes e uso de disco.",
    depth: 1,
    parentId: "core",
    position: [0.8, 0.4, 5.2],
    diagnosticsKey: "disk",
    children: ["lsblk", "disk-usage"],
  },
  {
    id: "logs",
    label: "Logs",
    type: "log",
    status: "idle",
    description: "Journals, erros recentes e evidencias de diagnostico.",
    depth: 1,
    parentId: "core",
    position: [-0.9, 0.2, -5.4],
    diagnosticsKey: "kernel-logs",
    children: ["journal-errors", "kernel-logs"],
  },
  {
    id: "actions",
    label: "Actions",
    type: "action",
    status: "idle",
    description: "Planos, aprovacoes, execucoes e historico local.",
    depth: 1,
    parentId: "core",
    position: [4.0, 2.9, 0.8],
    children: ["approval-layer", "action-logs"],
  },
  {
    id: "kernel-logs",
    label: "journalctl kernel",
    type: "log",
    status: "idle",
    description: "Eventos recentes do kernel para triagem.",
    depth: 2,
    parentId: "kernel",
    position: [-7.4, 2.2, -2.4],
    diagnosticsKey: "kernel-logs",
  },
  {
    id: "kernel-modules",
    label: "Modules",
    type: "kernel",
    status: "idle",
    description: "Modulos relacionados ao hardware ativo.",
    depth: 2,
    parentId: "kernel",
    position: [-6.9, 3.6, 0.2],
  },
  {
    id: "failed-units",
    label: "Failed units",
    type: "service",
    status: "idle",
    description: "Unidades systemd em falha.",
    depth: 2,
    parentId: "systemd",
    position: [-5.3, -3.4, 3.8],
    diagnosticsKey: "systemd",
  },
  {
    id: "journal-errors",
    label: "journalctl errors",
    type: "log",
    status: "idle",
    description: "Erros do boot atual com prioridade alta.",
    depth: 2,
    parentId: "systemd",
    position: [-2.5, -4.2, 4.4],
    diagnosticsKey: "kernel-logs",
  },
  {
    id: "monitors",
    label: "Monitors",
    type: "interface",
    status: "idle",
    description: "Monitores ativos do Hyprland.",
    depth: 2,
    parentId: "hyprland",
    position: [-3.5, 4.3, 4.6],
    diagnosticsKey: "hyprland",
  },
  {
    id: "workspaces",
    label: "Workspaces",
    type: "interface",
    status: "idle",
    description: "Workspaces e disposicao atual.",
    depth: 2,
    parentId: "hyprland",
    position: [-0.8, 5.3, 4.6],
    diagnosticsKey: "hyprland",
  },
  {
    id: "clients",
    label: "Clients",
    type: "interface",
    status: "idle",
    description: "Janelas clientes abertas no compositor.",
    depth: 2,
    parentId: "hyprland",
    position: [1.7, 4.4, 4.2],
    diagnosticsKey: "hyprland",
  },
  {
    id: "local-models",
    label: "Local models",
    type: "ai",
    status: "idle",
    description: "Modelos Ollama instalados no runtime local.",
    depth: 2,
    parentId: "ollama",
    position: [5.2, -3.4, -4.3],
    diagnosticsKey: "ollama",
  },
  {
    id: "qwen-coder",
    label: "Qwen Coder",
    type: "ai",
    status: "ready",
    description: "Modelo padrao do MVP para planejamento local.",
    depth: 2,
    parentId: "ollama",
    position: [2.9, -4.7, -5.0],
    diagnosticsKey: "ollama",
  },
  {
    id: "memory-edges",
    label: "Memory edges",
    type: "memory",
    status: "idle",
    description: "Arestas persistidas em SQLite e prontas para Graphiti.",
    depth: 2,
    parentId: "memory",
    position: [1.9, 5.5, -4.4],
  },
  {
    id: "graphiti-ready",
    label: "Graphiti-ready",
    type: "memory",
    status: "idle",
    description: "Contrato de memoria preparado para backend Graphiti futuro.",
    depth: 2,
    parentId: "memory",
    position: [-1.7, 5.8, -4.5],
  },
  {
    id: "bt-rfkill",
    label: "rfkill",
    type: "hardware",
    status: "idle",
    description: "Bloqueios de radio e estado de adaptadores.",
    depth: 2,
    parentId: "bluetooth",
    position: [-7.5, -1.7, -4.2],
    diagnosticsKey: "bluetooth",
  },
  {
    id: "bt-controller",
    label: "Controller",
    type: "hardware",
    status: "idle",
    description: "Controlador Bluetooth e visibilidade.",
    depth: 2,
    parentId: "bluetooth",
    position: [-6.2, -0.2, -5.3],
    diagnosticsKey: "bluetooth",
  },
  {
    id: "bt-systemd",
    label: "bluetooth.service",
    type: "service",
    status: "idle",
    description: "Servico bluetooth no systemd.",
    depth: 2,
    parentId: "bluetooth",
    position: [-6.7, -2.9, -2.8],
    diagnosticsKey: "systemd",
  },
  {
    id: "nm-devices",
    label: "nmcli device",
    type: "network",
    status: "idle",
    description: "Dispositivos de rede e estados NetworkManager.",
    depth: 2,
    parentId: "network",
    position: [-2.8, -5.8, -2.7],
    diagnosticsKey: "network",
  },
  {
    id: "dns-route",
    label: "DNS/Route",
    type: "network",
    status: "idle",
    description: "Rota e resolucao futuras para diagnostico.",
    depth: 2,
    parentId: "network",
    position: [-0.8, -6.2, -2.5],
  },
  {
    id: "pipewire",
    label: "PipeWire",
    type: "audio",
    status: "idle",
    description: "Pipeline de audio e status de sinks/sources.",
    depth: 2,
    parentId: "audio",
    position: [3.5, 5.0, 2.8],
    diagnosticsKey: "audio",
  },
  {
    id: "wireplumber",
    label: "WirePlumber",
    type: "audio",
    status: "idle",
    description: "Session manager do PipeWire.",
    depth: 2,
    parentId: "audio",
    position: [1.4, 5.4, 3.5],
    diagnosticsKey: "audio",
  },
  {
    id: "swapon",
    label: "swapon",
    type: "hardware",
    status: "idle",
    description: "Resumo de swap ativo.",
    depth: 2,
    parentId: "ram-zram",
    position: [-1.5, -6.2, 1.7],
    diagnosticsKey: "ram-zram",
  },
  {
    id: "zramctl",
    label: "zramctl",
    type: "hardware",
    status: "idle",
    description: "Dispositivos zram e uso atual.",
    depth: 2,
    parentId: "ram-zram",
    position: [0.6, -6.4, 1.9],
    diagnosticsKey: "ram-zram",
  },
  {
    id: "memory-pressure",
    label: "Pressure",
    type: "hardware",
    status: "idle",
    description: "Indicadores futuros de pressao de memoria.",
    depth: 2,
    parentId: "ram-zram",
    position: [-0.4, -6.7, -0.4],
  },
  {
    id: "approval-layer",
    label: "Approval Layer",
    type: "action",
    status: "approval",
    description: "Autorizacao explicita antes de comandos reais.",
    depth: 2,
    parentId: "actions",
    position: [5.7, 4.1, 1.3],
  },
  {
    id: "action-logs",
    label: "Action logs",
    type: "log",
    status: "idle",
    description: "Stdout, stderr, exit code e duracao das execucoes aprovadas.",
    depth: 2,
    parentId: "actions",
    position: [3.7, 5.1, -0.8],
  },
  {
    id: "pacman-cache",
    label: "Pacman cache",
    type: "package",
    status: "idle",
    description: "Analise segura de cache antes de limpeza.",
    depth: 2,
    parentId: "packages",
    position: [6.8, 2.7, -2.1],
    diagnosticsKey: "packages",
  },
  {
    id: "aur-updates",
    label: "AUR updates",
    type: "package",
    status: "idle",
    description: "Updates AUR via yay quando disponivel.",
    depth: 2,
    parentId: "packages",
    position: [6.4, 0.6, -3.0],
    diagnosticsKey: "packages",
  },
  {
    id: "lsblk",
    label: "lsblk",
    type: "hardware",
    status: "idle",
    description: "Topologia de blocos do sistema.",
    depth: 2,
    parentId: "disk",
    position: [1.2, 1.8, 7.0],
    diagnosticsKey: "disk",
  },
  {
    id: "disk-usage",
    label: "df -h",
    type: "hardware",
    status: "idle",
    description: "Uso de disco por filesystem.",
    depth: 2,
    parentId: "disk",
    position: [2.8, -0.2, 6.5],
    diagnosticsKey: "disk",
  },
  {
    id: "end4-shell",
    label: "End-4 shell",
    type: "interface",
    status: "idle",
    description: "Hooks futuros para Quickshell/End-4.",
    depth: 2,
    parentId: "quickshell",
    position: [2.7, -4.3, 4.8],
  },
  {
    id: "dock-events",
    label: "Dock events",
    type: "interface",
    status: "idle",
    description: "Eventos futuros de dock e shell.",
    depth: 2,
    parentId: "quickshell",
    position: [0.3, -5.1, 4.5],
  },
  {
    id: "mesa",
    label: "Mesa",
    type: "hardware",
    status: "idle",
    description: "Stack grafica Mesa/RADV quando aplicavel.",
    depth: 2,
    parentId: "gpu",
    position: [6.9, -0.9, 3.9],
    diagnosticsKey: "gpu",
  },
  {
    id: "vulkan",
    label: "Vulkan",
    type: "hardware",
    status: "idle",
    description: "Capabilities graficas futuras.",
    depth: 2,
    parentId: "gpu",
    position: [5.6, -2.7, 4.5],
    diagnosticsKey: "gpu",
  },
  {
    id: "hypr-gpu",
    label: "Hyprland/GPU",
    type: "interface",
    status: "idle",
    description: "Relacao entre compositor, monitor e GPU.",
    depth: 2,
    parentId: "gpu",
    position: [6.9, 0.7, 2.1],
    diagnosticsKey: "hyprland",
  },
];

export const neuralConnections: NeuralConnection[] = neuralNodes
  .filter((node) => node.parentId)
  .map((node) => ({
    id: `${node.parentId}-${node.id}`,
    from: node.parentId ?? "core",
    to: node.id,
    status: node.status,
    label: node.label,
    strength: node.depth === 1 ? 0.86 : 0.55,
  }));

export const nodeById = new Map(neuralNodes.map((node) => [node.id, node]));

export function getNodePath(nodeId: string): NeuralNode[] {
  const path: NeuralNode[] = [];
  let current = nodeById.get(nodeId);
  while (current) {
    path.unshift(current);
    current = current.parentId ? nodeById.get(current.parentId) : undefined;
  }
  return path;
}
